[package]
name = "nidrs-diesel"
version = "0.1.0"
authors = ["WumaCoder <wumacoder@gmail.com>"]
description = "Nidrs & Diesel integration"
keywords = ["nidrs", "orm", "diesel", "web", "database"]
categories = ["network-programming", "asynchronous", "web-programming::http-server", "web-programming::websocket"]
publish = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
diesel = { version = "2.2.3", features = ["r2d2"] }
nidrs = { workspace = true }
nidrs-macro = { workspace = true }
nidrs-extern = { workspace = true }

[features]
default = ["sqlite"]
mysql = ["diesel/mysql"]
postgres = ["diesel/postgres"]
sqlite = ["diesel/sqlite"]
